services:
    icap_notification.manager:
        class: Icap\NotificationBundle\Service\Manager
        arguments: [@service_container]

    icap_notification.twig.notification_extension:
        class: Icap\NotificationBundle\Twig\NotificationExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }
